name: Semantic release

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegúrate de tener todo el historial para Semantic Release

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev

      - name: Rebase local changes onto the latest origin/main
        run: |
         git fetch origin
         git rebase origin/main

      - name: Push changes
        run: |
         git push https://github.com/vazqueztomas/pycurrencies main

      - name: Semantic Release
        uses: python-semantic-release/python-semantic-release@v8.0.0
        with:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
