name: Semantic release

on:
    push:
      branches: ["main"]
    pull_request:
      branches: ["main"]

permissions:
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Asegúrate de tener todo el historial para Semantic Release

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install global dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipx==1.2.0

      - name: Set Git Identity
        run: |
          set -e
          git fetch -v -v -v --all --unshallow || true
          git switch "${{github.head_ref}}" || git checkout "${{github.head_ref}}"
          git config user.name "$(git log -1 --pretty=format:'%an' | xargs)"
          git config user.email "$(git log -1 --pretty=format:'%ae' | xargs)"

      - name: Update Version and Changelog
        run: |
          set -e
          pipx install --verbose python-semantic-release==8.3.0
          semantic-release -v version --no-vcs-release --no-commit
          differences=$(git diff)

          if [ -z "$differences" ]; then
            echo "No changes detected, exiting..."
            exit 0
          fi

          echo "The version and/or Changelog is outdated, updating..."
          echo "$differences"

          git add --all --verbose
          git commit --verbose -m "chore(release): update version and changelog"
          git push --verbose

          echo "Push successful, exiting..."
          exit 0
